require("dotenv").config();

module.exports = {
  apps: [
    {
      name: "kitchen-backend",
      script: "dist/index.js",
      cwd: __dirname,
      instances: 1,
      exec_mode: "fork",
      watch: false,
      autorestart: true,
      max_memory_restart: "300M",
      env: {
        NODE_ENV: "development",
        PORT: 4001,
        STATIC_DIR: "./public",
        MARIADB_PORT: 3306,
        MARIADB_DATABASE: "kitchen",
        MARIADB_USER: "kitchen",
        MARIADB_PASSWORD: "kitchen",
        MARIADB_ROOT_PASSWORD: "root",
        DATABASE_URL: "mysql://kitchen:kitchen@localhost:3306/kitchen",
        GEMINI_API_KEY: process.env.GEMINI_API_KEY || "",
        AUTH_ISSUER: process.env.AUTH_ISSUER || "https://auth.sinul.es",
      },
      env_production: {
        NODE_ENV: "production",
        PORT: 4001,
        STATIC_DIR: "./public",
        MARIADB_PORT: 3306,
        MARIADB_DATABASE: "kitchen",
        MARIADB_USER: "kitchen",
        MARIADB_PASSWORD: "kitchen",
        MARIADB_ROOT_PASSWORD: "root",
        DATABASE_URL: "mysql://kitchen:kitchen@localhost:3306/kitchen",
        GEMINI_API_KEY: process.env.GEMINI_API_KEY || "",
        AUTH_ISSUER: process.env.AUTH_ISSUER || "https://auth.sinul.es",
      },
      out_file: "./logs/out.log",
      error_file: "./logs/error.log",
      merge_logs: true,
      time: true,
    },
    {
      name: "kitchen-backend-dev",
      script: "src/index.ts",
      interpreter: "node_modules/.bin/tsx",
      cwd: __dirname,
      instances: 1,
      exec_mode: "fork",
      watch: ["src"],
      ignore_watch: ["node_modules", "dist", "logs", "public"],
      autorestart: true,
      env: {
        NODE_ENV: "development",
        PORT: 4001,
        STATIC_DIR: "./public",
        MARIADB_PORT: 3306,
        MARIADB_DATABASE: "kitchen",
        MARIADB_USER: "kitchen",
        MARIADB_PASSWORD: "kitchen",
        MARIADB_ROOT_PASSWORD: "root",
        DATABASE_URL: "mysql://kitchen:kitchen@localhost:3306/kitchen",
        GEMINI_API_KEY: process.env.GEMINI_API_KEY || "",
        AUTH_ISSUER: process.env.AUTH_ISSUER || "https://auth.sinul.es",
      },
      out_file: "./logs/dev-out.log",
      error_file: "./logs/dev-error.log",
      merge_logs: true,
      time: true,
    },
  ],
};
