import type { Product } from '@/types/product'

export const mockProducts: Product[] = [
  {
    id: '1',
    name: 'Leche entera',
    photoUrl: 'https://images.openfoodfacts.org/images/products/000/000/000/1/front.jpg',
    description: 'Leche entera de vaca, brick de 1 litro.',
    quantityRemaining: 1,
    quantityTotal: 1,
    category: 'Lácteos',
    expirationDate: '2026-07-30',
    comment: 'Comprada en el Mercadona.',
  },
  {
    id: '2',
    name: 'Huevos camperos',
    photoUrl: 'https://images.openfoodfacts.org/images/products/000/000/000/2/front.jpg',
    description: 'Docena de huevos camperos talla M.',
    quantityRemaining: 8,
    quantityTotal: 12,
    category: 'Huevos',
    expirationDate: '2026-08-05',
    comment: '',
  },
  {
    id: '3',
    name: 'Yogur natural',
    photoUrl: 'https://images.openfoodfacts.org/images/products/000/000/000/3/front.jpg',
    description: 'Pack de 4 yogures naturales sin azúcar.',
    quantityRemaining: 2,
    quantityTotal: 4,
    category: 'Lácteos',
    expirationDate: '2026-07-28',
    comment: '',
  },
  {
    id: '4',
    name: 'Tomates',
    photoUrl: 'https://images.openfoodfacts.org/images/products/000/000/000/4/front.jpg',
    description: 'Bolsa de tomates de rama.',
    quantityRemaining: 5,
    quantityTotal: 6,
    category: 'Verduras',
    expirationDate: '2026-07-26',
    comment: 'Comprobar si están maduros.',
  },
  {
    id: '5',
    name: 'Pechuga de pollo',
    photoUrl: 'https://images.openfoodfacts.org/images/products/000/000/000/5/front.jpg',
    description: 'Filetes de pechuga de pollo, bandeja de 500g.',
    quantityRemaining: 1,
    quantityTotal: 1,
    category: 'Carne',
    expirationDate: '2026-07-24',
    comment: 'Congelar si no se usa pronto.',
  },
  {
    id: '6',
    name: 'Queso curado',
    photoUrl: 'https://images.openfoodfacts.org/images/products/000/000/000/6/front.jpg',
    description: 'Cuña de queso curado de oveja.',
    quantityRemaining: 1,
    quantityTotal: 1,
    category: 'Lácteos',
    expirationDate: '2026-09-10',
    comment: '',
  },
]
